### ISSUE TITLE
[Build failed] OPENCV_XFEATURES2D_NONFREE NOT PRESENT

### ISSUE THREAD

**Issue by sqn175** [youkely/InfrasCal#1]
Hi,

Thanks for your great work! I'm trying to compile InfrasCal, however some errors occurs (see attached file "make_error.log"). 

I installed the OpenCV in the directory `/data1/home/slam/Documents/sources/installed` using `-DCMAKE_INSTALL_PREFIX=/data1/home/slam/Documents/sources/installed`. 
Accordingly, I changed the `LibraryConfig.cmake` as follows:
![image](https://user-images.githubusercontent.com/10163611/93455833-73bfd980-f90f-11ea-8b00-7b3c973622dd.png)

The cmake outputs are attached to "cmake.log"
[cmake.log](https://github.com/youkely/InfrasCal/files/5238171/cmake.log). 
It prints "OPENCV_XFEATURES2D_NONFREE NOT PRESENT". However, I DO have the 'opencv2/xfeatures2d/nonfree.hpp' header file in the directory:
![image](https://user-images.githubusercontent.com/10163611/93455634-33605b80-f90f-11ea-91e9-f15c334e3783.png)

[make_error.log](https://github.com/youkely/InfrasCal/files/5238107/make_error.log)

Is there any solution? Many thanks!

Best wishes
Qin Shi

**Comment by youkely** [comment]
l74 in LibraryConfig.cmake
check_include_file_cxx(opencv2/xfeatures2d/nonfree.hpp HAVE_OPENCV_XFEATURES2D_NONFREE).
Did you check why this line produces false for HAVE...NONFREE?

**Comment by sqn175** [comment]
Thanks for your reply. The build succeeds after a clean rebuild. I'll close the issue.
