### ISSUE TITLE
about the solvePnPRadialRansac funciton

### ISSUE THREAD

**Issue by sicong-li** [youkely/InfrasCal#11]
in your code : https://github.com/youkely/InfrasCal/blob/b36103b3993fd060b643d29c84aec75149d04c84/src/infrastr_calib/InfrastructureCalibration.cc#L2455

there have a clip:

        for (size_t k = 0; k < corr2D3Ds.size(); ++k)
            {
                const std::pair<Point2DFeaturePtr, Point3DFeaturePtr> corr2D3D = corr2D3Ds.at(k);
                Eigen::Vector3d P2 = corr2D3D.second->point();
                Eigen::Vector3d P1 = transformPoint(H_inv, P2);
                Eigen::Vector2d p1_pred(P1[0]/P1[2], P1[1]/P1[2]);
                double p1_pred_norm = p1_pred.norm();
                p1_pred(0) = p1_pred(0)/p1_pred_norm;
                p1_pred(1) = p1_pred(1)/p1_pred_norm;
                const Point2DFeatureConstPtr& f1 = corr2D3D.first;
                Eigen::Vector2d p1_pixel(f1->keypoint().pt.x - cxcy[0],
                                         f1->keypoint().pt.y - cxcy[1]);
                if(p1_pixel(0) * P1[0] + p1_pixel(1) * P1[1] < 0)
                    continue;
                Eigen::Vector2d p1_pred_proj;
                p1_pred_proj(0) = p1_pred(0)*p1_pred(0)*p1_pixel(0)
                                  + p1_pred(0)*p1_pred(1)*p1_pixel(1);
                p1_pred_proj(1) = p1_pred(1)*p1_pred(1)*p1_pixel(1)
                                  + p1_pred(0)*p1_pred(1)*p1_pixel(0);
                double err = hypot(p1_pixel(0) - p1_pred_proj(0),
                                   p1_pixel(1) - p1_pred_proj(1));
                if (!isnormal(err) || err > k_reprojErrorThresh)
                {
                    continue;
                }

                inliersIds.push_back(k);
            }

I dont konw why what  `p1_pred(0) = p1_pred(0)/p1_pred_norm; `  and `p1_pred_proj(0) = p1_pred(0)*p1_pred(0)*p1_pixel(0) + p1_pred(0)*p1_pred(1)*p1_pixel(1);`  doing? can you explain to me or share some paper link?
@youkely 
@tsattler

**Comment by youkely** [comment]
p1_pred_proj is to calculate the "radial reprojection error", you can search the term in the paper for details.
