### ISSUE TITLE
what is "Rig Poses" mean？

### ISSUE THREAD

**Issue by sicong-li** [youkely/InfrasCal#12]
In your paper there have "Rig Poses"  and "Camera-Rig Extrinsics"  ，I want to konw what is this mean?

**Comment by youkely** [comment]
“Rig Pose” means the pose of the camera system in the world, namely world_T_rig. The rig frame can be set as a fixed frame in the camera system. In this rig, there are several cameras, so we have the camera-rig extrinsics, which is the "Camera-Rig Extrinsics", namely rig_T_cami.
