### ISSUE TITLE
Run calib without map folder

### ISSUE THREAD

**Issue by vswdigitall** [youkely/InfrasCal#13]
Hi,

Can i run calib without map folder?

./bin/infrastr_calib --camera-count 3 --output /media/ubuntu/data/1639127956941/results --input /media/ubuntu/data/1639127956941 -v --camera-model pinhole-radtan --save

**Comment by tsattler** [comment]
The map is used to compute the calibration. Without a map, this software is not able to calibrate images.

**Comment by vswdigitall** [comment]
And where i can get db and sift data?

**Comment by tsattler** [comment]
The database can be created using Colmap and the vocabulary can be created using the DBoW2 library.

**Comment by vswdigitall** [comment]
Do you have description of these steps?

**Comment by tsattler** [comment]
Colmap has a good tutorial: https://colmap.github.io/tutorial.html

Here is an example for using DBoW2: https://github.com/youkely/InfrasCal/blob/master/src/examples/train_voctree.cc

**Comment by vswdigitall** [comment]
Ok. Thank you.
