### ISSUE TITLE
[Table1.] Evaluation with a scale

### ISSUE THREAD

**Issue by KyanainsGate** [youkely/InfrasCal#14]
Hi, cool work! And thank you for sharing the code!

Btw, I have a question about the published paper; How did you evaluate the extrinsics calibration performance with the "centimeter" scale?
Since this work is based on the COLMAP, if I’m not wrong, the model can only take a pose on non-scaled coordinates.

Best regards,

**Comment by youkely** [comment]
During mapping process, we will align the map to correct scale using the alignment function provided by Colmap. The scale is derived from some objects that we already know the correct length, e.g. a box with 1m width. Another way could be to use the multi-cam system with known extrinsics(e.g. stereo cameras) to reconstruct the scene, then the map is produced with correct scale.

**Comment by KyanainsGate** [comment]
Thank you for your quick response! 
As you did in your paper, I'm also going to prepare the object having a known scale.
