### ISSUE TITLE
Question about result file.

### ISSUE THREAD

**Issue by TheCuriousJoe** [youkely/InfrasCal#15]
![image](https://user-images.githubusercontent.com/28175538/194991816-1d943ee9-9036-43fd-bd17-f575d8f272d6.png)

The result file is showed above. 
My questions are:
1. what's the frames.sg and how can i visualize it?
2. Why the subfolder "frames" is empty?

Thanks!

**Comment by youkely** [comment]
1. frames.sg contains all the raw and intermediate data that are used to process infras-calib, it is of binary format and not used for visualization. (https://github.com/youkely/InfrasCal/blob/b36103b3993fd060b643d29c84aec75149d04c84/src/sparse_graph/SparseGraph.cc#L1151)
2. we use some "save" function from camodocal lib and it produces the empty subfolder which is not used. You can just ignore it.

**Comment by TheCuriousJoe** [comment]
> 1. frames.sg contains all the raw and intermediate data that are used to process infras-calib, it is of binary format and not used for visualization. (https://github.com/youkely/InfrasCal/blob/b36103b3993fd060b643d29c84aec75149d04c84/src/sparse_graph/SparseGraph.cc#L1151
>    )
> 2. we use some "save" function from camodocal lib and it produces the empty subfolder which is not used. You can just ignore it.

Thanks for the quick reply! Are there any visualization function in the project?

**Comment by youkely** [comment]
cameras.txt and images.txt are in colmap format. see (https://github.com/youkely/InfrasCal/blob/master/src/infrastr_calib/InfrastructureCalibration.cc#L642)

you should be able to visualize it using colmap "import model from".

**Comment by TheCuriousJoe** [comment]
> cameras.txt and images.txt are in colmap format. see (https://github.com/youkely/InfrasCal/blob/master/src/infrastr_calib/InfrastructureCalibration.cc#L642)
> 
> you should be able to visualize it using colmap "import model from".

I get it! Thanks again!
