### ISSUE TITLE
How to work by using the results of Camodocal?

### ISSUE THREAD

**Issue by liuwenlei2018** [youkely/InfrasCal#17]
I'm very interested in your work.It's wonderful. 
First, I ran it in camodocal and saved the calculation results, including 2D and 3D features and map information. The results are then used as input to infrascal for multi camera calibration. Can infrascal work properly in this situation? If it works, what other parameters need to be modified?

**Comment by youkely** [comment]
Hi, thanks for your interest.

If I understand correctly, you want to use the map generated from camodocal for multi-camera calibration. Currently Infrascal only supports Colmap format for input map. However, you can easily modify the codes to adapt to camodocal format. Check "loadmap"(https://github.com/youkely/InfrasCal/blob/b36103b3993fd060b643d29c84aec75149d04c84/src/infrastr_calib/InfrastructureCalibration.cc#L49) function for infrascal and substitute the "readFromColmap" with "readFromBinaryFile" in a proper way. With that you should be able to load the map generated from camodocal.

Best,
Yukai

**Comment by liuwenlei2018** [comment]
Hi,Thank you very much for your prompt response. I modified the code to load the Camodocal map, but the following error occurred: "Assertion 'px!=0' failed". This problem has troubled me for several days. Have you ever encountered this problem?

**Comment by youkely** [comment]
Sorry, I have not encountered it before. This is probably caused by some false operation on shared pointer on loading the map.  Maybe you can add more log and see where the program crashes.

**Comment by liuwenlei2018** [comment]
OK,  Thank you very much.
