### ISSUE TITLE
How to get the map at the required format?

### ISSUE THREAD

**Issue by Mikor-mkr** [youkely/InfrasCal#4]
Hello,

I am interested in using your package, thanks for working on something that is really missing. My question is how to get the map at the required format, I have a point cloud made out of the frames from agisoft, how should I export/parse it in the proper way?

**Comment by youkely** [comment]
Hi,

Thanks for your interests in this project. We use colmap format as the data input. The readdata function is in https://github.com/youkely/InfrasCal/blob/master/src/sparse_graph/SparseGraph.cc#L526. You can also check the colmap data format at https://colmap.github.io/format.html.
