### ISSUE TITLE
how to get the test dataset on the paper?

### ISSUE THREAD

**Issue by angiend** [youkely/InfrasCal#5]
great work!
What are the test data in the paper?  Is it open source?  Can you share the link? 
i would like to know  how to record the dataset for surround view camera

**Comment by youkely** [comment]
Sorry, the test data is not publicly available. But if you have such a camera-rig, you may shoot a video with it in high-frame-rate mode (120fps or higher). You may synchronize them with some tricks, e.g. use a flashlight to pick a start frame and extract all the images from videos of all cameras.

**Comment by angiend** [comment]
thanks for your reply.
i tried use the kitti dataset to reconstrut the 3d map by colmap, using the two gray camera front view.
but it seems error,i don't exactly  know whats wrong.
so , when you reconstrut the 3d map,are the following conditions necessary?
or other constraint condition？ would you give some advice?
1. camere ins parameter
2. loopcloser
3. ...

**Comment by youkely** [comment]
I haven't try the kitti datasets. For 3d reconstruction, I don't necessarily make any constraints. You may try RobotSeason datasets as shown in the paper, which already provide the map in colmap format.

**Comment by angiend** [comment]
thank you very much, i try it later,thanks.
great work
