### ISSUE TITLE
Average radial reprojection error over all frames: -nan px

### ISSUE THREAD

**Issue by angiend** [youkely/InfrasCal#6]
i test the kitti dataset "2011_09_26_drive_0020_sync" 
and get the 3d map by colmap.
![Screenshot from 2021-10-14 10-48-01](https://user-images.githubusercontent.com/39428557/137242306-0bed606a-983d-4880-9df8-9d45463dc76d.png)

when i use the map to get the extrinsic between the camera_0 and camera_1

![12](https://user-images.githubusercontent.com/39428557/137244561-d678968f-f238-4463-9a28-484a34620e4e.png)

my test data also come from the train data,
![11](https://user-images.githubusercontent.com/39428557/137244223-82801672-1348-4294-818b-6c0e1a5a2411.png)

**Comment by youkely** [comment]
Are the two cameras parallel? InRaSU is not suitable for parallel cameras.

**Comment by angiend** [comment]
thanks for your reply.

_Are the two cameras parallel? InRaSU is not suitable for parallel cameras._


Do you mean that InRaSU is suitable for surround view camera ,not for parallel cameras ? is there other model suitable for parallel cameras? Kitti dataset front-view cameras do look a little parallel

**Comment by youkely** [comment]
You can try use InRaS. You may refer to Section 4 Implementation/Limitations in the eccv paper for details.

**Comment by angiend** [comment]
ok, thanks a lot
