### ISSUE TITLE
Extrinsic Parameter Reference

### ISSUE THREAD

**Issue by pateljayam** [youkely/InfrasCal#9]
Hello,

I have 6 Camera configuration and I am running your package to generate extrinsic configuration for them.

Are all the output extrinsic parameters in reference to cam0? or are they in reference to the previous camera? For example, came1 in reference to cam0, cam2 in reference to cam1 and so on.

I really appreciate your help.

Regards
PJ

**Comment by youkely** [comment]
All of them are in reference to cam0.

**Comment by pateljayam** [comment]
Thank you for the clarification.
